### ISSUE TITLE
Publish to ``conda-forge``

### ISSUE THREAD

**Issue by davnn** [junjihashimoto/py-stacked-dag#2]
Hi, it would be great if the package could be installed with ``conda``.  Would you be open to registering it with ``conda-forge``?

Because the package is python-only, it should be enough to submit a pull request to <https://github.com/conda-forge/staged-recipes/> using a ``meta.yml`` generated with [grayskull](https://github.com/conda-incubator/grayskull).

I would also be willing to open the pull request if you'd prefer that.

**Comment by junjihashimoto** [comment]
It would be nice!
I'm not familiar with conda-forge.
If you open the PR, it will be helpful.

**Comment by davnn** [comment]
I just saw that the LICENSE file is not included in the PyPI published release. It would be necessary to add the LICENSE file to the release before we can submit the PR to conda-forge.

**Comment by junjihashimoto** [comment]
@davnn I uploaded 0.3.4 with LICENSE file.

**Comment by davnn** [comment]
Thanks! The PR is ready, see https://github.com/conda-forge/staged-recipes/pull/21068. Please leave a quick comment that you confirm the PR as the package author/maintainer.

**Comment by davnn** [comment]
The package is available on conda forge now 👍
